name: action debug
run-name: ${{ github.actor }} - ${{ github.event_name }}
on: 
    push:
       branches: 
        - ci/github

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: get branch name
      id: get-branch-name
      run:   echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
    - name: debug
      run: |
        echo "branch name: ${{ steps.get-branch-name.outputs.branch }}"