name: action debug
run-name: ${{ github.actor }} - ${{ github.event_name }}
on: 
    push:
       branches: 
        - ci/github

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: echo ref
      run:   echo ${{ github.ref_name }}